In [109]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from ast import literal_eval

In [174]:
data_df = pd.read_csv('100_random_cleaned_0908.csv')
data_df.head()

Unnamed: 0    cuisine_SP  garlic  chocolate  tomato  vanilla  lemon  \
0           0            []       0          1       0        0      0   
1           1     ['Asian']       0          0       0        0      0   
2           2   ['Mexican']       1          0       0        0      0   
3           3            []       0          0       0        0      0   
4           4  ['American']       1          0       0        0      0   

   parsley  honey  vinegar  ...  broth  basil  shallot  parmesan  buttermilk  \
0        0      0        0  ...      0      0        0         0           0   
1        0      0        1  ...      0      1        0         0           0   
2        0      0        0  ...      1      0        0         0           0   
3        0      0        0  ...      1      0        0         0           0   
4        0      0        0  ...      0      0        0         0           0   

   fresh pepper  almonds  chili powder  dry yeast  orange  
0             0        0             0          0       0  
1             0        0             0          0       0  
2             0        0             1          0       0  
3             0        0             0          0       0  
4             0        0             0          0       0  

[5 rows x 22 columns]

In [175]:
data_df.drop(columns='Unnamed: 0', inplace=True)

In [176]:
data_df.loc[2,'cuisine_SP'] == ['Mexican']

False

In [178]:
responses_df = pd.get_dummies(data_df.cuisine_SP)

In [179]:
responses_df.rename(columns={"['American']": 'american',
                        "['Asian']": 'asian',
                        "['Creole', 'Cajun']": 'cajun',
                        "['English', 'Scottish', 'British', 'European']": 'english',
                        "['Indian', 'Asian']": 'indian',
                        "['Mediterranean', 'European', 'Greek']": 'greek',
                        "['Mediterranean', 'French', 'European']": 'french',
                        "['Mediterranean', 'Italian', 'European']": 'italian',
                        "['Mexican']": 'mexican',
                        "['Middle Eastern']": 'middle eastern',
                        "['Southern']": 'southern',
                        "['Vietnamese', 'Asian']": 'vietnamese'
                       }, inplace=True)
responses_df

american  asian  cajun  english  indian  greek  french  italian  mexican  \
0          0      0      0        0       0      0       0        0        0   
1          0      1      0        0       0      0       0        0        0   
2          0      0      0        0       0      0       0        0        1   
3          0      0      0        0       0      0       0        0        0   
4          1      0      0        0       0      0       0        0        0   
..       ...    ...    ...      ...     ...    ...     ...      ...      ...   
95         0      0      0        0       0      0       0        0        1   
96         0      0      0        0       0      0       0        0        0   
97         0      0      0        0       0      0       0        0        0   
98         0      0      0        0       0      0       0        0        0   
99         0      0      0        0       0      0       0        0        0   

    middle eastern  southern  vietnamese  []  
0                0         0           0   1  
1                0         0           0   0  
2                0         0           0   0  
3                0         0           0   1  
4                0         0           0   0  
..             ...       ...         ...  ..  
95               0         0           0   0  
96               0         0           0   1  
97               0         0           0   1  
98               0         0           0   1  
99               0         0           0   1  

[100 rows x 13 columns]

In [180]:
y_raw = responses_df.mexican.values.reshape(-1,1)

In [193]:
X_raw = mexican_df.drop(columns=['cuisine_SP','Unnamed: 0'])
X_raw

garlic  chocolate  tomato  vanilla  lemon  parsley  honey  vinegar  flour  \
0        0          1       0        0      0        0      0        0      0   
1        0          0       0        0      0        0      0        1      0   
2        1          0       0        0      0        0      0        0      0   
3        0          0       0        0      0        0      0        0      0   
4        1          0       0        0      0        0      0        0      0   
..     ...        ...     ...      ...    ...      ...    ...      ...    ...   
95       0          0       0        1      0        0      0        0      0   
96       1          0       0        0      0        0      0        1      0   
97       0          0       0        0      0        0      1        0      0   
98       0          0       0        0      0        0      0        0      0   
99       1          0       0        0      0        0      0        0      0   

    cream  broth  basil  shallot  parmesan  buttermilk  fresh pepper  almonds  \
0       0      0      0        0         0           0             0        0   
1       0      0      1        0         0           0             0        0   
2       0      1      0        0         0           0             0        0   
3       0      1      0        0         0           0             0        0   
4       0      0      0        0         0           0             0        0   
..    ...    ...    ...      ...       ...         ...           ...      ...   
95      0      0      0        0         0           0             0        0   
96      0      0      0        0         0           0             0        0   
97      0      0      0        0         0           0             0        0   
98      0      0      0        0         0           0             0        0   
99      0      0      0        1         0           0             0        0   

    chili powder  dry yeast  orange  
0              0          0       0  
1              0          0       0  
2              1          0       0  
3              0          0       0  
4              0          0       0  
..           ...        ...     ...  
95             0          0       0  
96             0          0       0  
97             0          0       0  
98             0          0       1  
99             0          0       0  

[100 rows x 20 columns]

In [194]:
np.ravel(y_raw)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=uint8)

In [195]:
X_train, X_test, y_train, y_test = train_test_split(X_raw, y_raw, random_state=42)

In [196]:
dtr = DecisionTreeRegressor(random_state = 42).fit(X_train, np.ravel(y_train))


In [197]:
dtr.score(X_train, y_train)

0.5659722222222222

In [198]:
y_train_pred = dtr.predict(X_train)

In [199]:
y_train_pred

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ,
       0.5 , 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ])

In [200]:
y_test_pred = dtr.predict(X_test)

In [201]:
y_test_pred

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.5 , 0.  , 0.  ])

In [202]:
dtr.feature_importances_

array([0.        , 0.0204499 , 0.        , 0.08272913, 0.06134969,
       0.        , 0.        , 0.        , 0.02629273, 0.03505697,
       0.4601227 , 0.        , 0.        , 0.        , 0.09743159,
       0.        , 0.        , 0.11431781, 0.10224949, 0.        ])

In [203]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 42,
 'splitter': 'best'}

In [204]:
dtr.score(X_test, y_test)

0.0

In [107]:
dtr.get_depth()

0